server:
  port: 8088 # 后端服务启动在这个端口
  tomcat:
    max-http-form-post-size: 20MB  # 支持 Base64 头像上传，默认 2MB 不够

spring:
  application:
    name: skill-help-backend
  
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 这里的 skill_help_db 就是咱们刚刚成功创建的数据库名
    url: jdbc:mysql://127.0.0.1:3306/skill_help_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    # 注意：请将 root 和你的数据库密码替换为你真实的配置
    username: root
    password: admin123 # 【TODO】改写成你的本地数据库密码

  # 允许大请求体（Base64图片可能很大）
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# MyBatis-plus 进阶配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动转换映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 在控制台打印生成的SQL语句，方便毕设找bug
